import { type Project, ProjectCategory } from "./types";

export const projects: Project[] = [
    {
        id: "personal-1",
        title: "CMS Storefront",
        description:
            "An E-Commerce Store with its very own Admin CMS to dynamically manage a multitude of stores",
        image: "/store-cms-frontend.png",
        category: ProjectCategory.Personal,
        technologies: [
            "Next.js",
            "TypeScript",
            "Zustand",
            "Tailwind CSS",
            "Stripe",
            "Shadcn UI",
        ],
        liveDemoUrl: "https://store-cms-frontend.vercel.app/",
        status: "recently completed",
    },
    {
        id: "personal-2",
        title: "CMS Store Portal",
        description:
            "An E-Commerce Store Admin portal to dynamically manage a multitude of stores",
        image: "/store-cms-admin.png",
        category: ProjectCategory.Personal,
        technologies: [
            "Next.js",
            "Zustand",
            "TypeScript",
            "Tailwind CSS",
            "Prisma",
            "Stripe",
            "Cloudinary",
            "Clerk Auth",
            "Postgresql",
            "Shadcn UI",
        ],
        liveDemoUrl: "https://next15-store-cms.vercel.app/",
        status: "recently completed",
    },
    {
        id: "personal-3",
        title: "Windows 11",
        image: "/win-11.png",
        category: ProjectCategory.Personal,
        technologies: ["React.js", "Vite"],
    },
    {
        id: "personal-4",
        title: "The Midnight Graveyard",
        image: "/themidnightgraveyard.png",
        category: ProjectCategory.Personal,
        liveDemoUrl: "https://themidnightgraveyard.netlify.app/",
        technologies: ["React.js", "Vite"],
    },
    {
        id: "personal-5",
        title: "Better App",
        image: "/better-app.png",
        category: ProjectCategory.Personal,
        liveDemoUrl: "https://better-app-five.vercel.app/",
        technologies: [
            "Next.js",
            "TypeScript",
            "Tailwind CSS",
            "Prisma",
            "Better Auth",
            "Postgresql",
            "Shadcn UI",
        ],
    },
    {
        id: "personal-6",
        title: "CarHub",
        image: "/carhub.png",
        category: ProjectCategory.Personal,
        liveDemoUrl: "https://carhub-deal.vercel.app/",
        technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Shadcn UI"],
        status: "recently completed",
    },
    {
        id: "personal-7",
        title: "Weather App",
        image: "/weather-app.png",
        category: ProjectCategory.Personal,
        liveDemoUrl: "https://globalweatherapp.vercel.app/",
        technologies: ["Vue.js", "Vite"],
    },
    {
        id: "personal-8",
        title: "Discordant",
        image: "/discordant.png",
        category: ProjectCategory.Personal,
        liveDe
